### PR TITLE
Add support for redhat based distributions.

### PR DESCRIPTION
**Pull request by jakzal**

### CODE REVIEW

**Comment by odolbeau** [comment]
:+1: 

Can you update the metadata file to bump the version and add new `supports` ?
Thanks. :)

**Comment by jakzal** [comment]
Sure. Sorry, that's the first time I contribute to a chef cookbook ;)

**Comment by jakzal** [comment]
Done :)

**Comment by odolbeau** [comment]
Thanks. :)

**Comment by odolbeau** [comment]
New version published on supermarket. :)
https://supermarket.chef.io/cookbooks/blackfire

Congrats for your first contribution to a cookbook. ;)

**Comment by jakzal** [comment]
:beer:

**Pull request merged**
